name: Render Website Videos

on:
  workflow_dispatch:  # Allows you to trigger the action manually from the GitHub UI

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install script deps
        run: npm ci
        working-directory: ./scripts

      # 🔑 Install deps for the Remotion project
      - name: Install Remotion deps
        run: npm ci
        working-directory: ./remotion/website-video-render

      - name: Run render script
        run: node render-from-list.js
        working-directory: ./scripts

      - name: Upload rendered videos
        uses: actions/upload-artifact@v4
        with:
          name: rendered-mp4
          path: remotion/website-video-render/out/*.mp4
